Support id/class in built-in components
lovasoa/SQLpage pull request #182
Opened 2024-01-10 13:02 UTC by lorefnon

Hello, currently some of the components support id/class like the form components. 

I'd like to propose that these be supported in all the built in components where it makes sense. 

I am primarily interested in id which is useful for anchor targeting (`<a href="#id">Some panel</a>`). It makes it possible to have links that scroll to a particular card or chart. For components that have a top level container, the id can be added to the container, and for those that don't have it can be added as a separate anchor.

class is nice to have for styling convenience. 

Hope this feature is acceptable. Happy to revise if you have any suggestions.

2024-01-10 19:51 UTC, lovasoa requested changes
Great, that sounds useful !

I'll merge, but all of the new attributes need to be documented first in https://github.com/lovasoa/SQLpage/blob/main/examples/official-site/sqlpage/migrations/01_documentation.sql (and other doc files in https://github.com/lovasoa/SQLpage/tree/main/examples/official-site/sqlpage/migrations )

2024-01-10 19:51 UTC, lovasoa commented on sqlpage/templates/card.handlebars
>          <div class="col">
Wouldn't you like to allow giving individual cards an id ? This would allow linking to one card in particular.

2024-01-10 19:51 UTC, lovasoa commented on sqlpage/templates/form.handlebars
> +    {{#if id}}action="#{{id}}"{{/if}}
This behavior needs to be documented

2024-01-10 19:51 UTC, lovasoa commented on sqlpage/templates/hero.handlebars
> +{{#if id}}<a id="{{id}}" />{{/if}}
why not directly on the header element ?

2024-01-12 15:53 UTC, lorefnon commented
Hi @lovasoa - I have added the docs and updated as per above comments.

2024-01-12 22:05 UTC, lovasoa approved these changes
:confetti_ball:

2024-01-12 22:05 UTC, merged