Parse JSON menu_item for SQLite
lovasoa/SQLpage pull request #432
Opened 2024-06-20 05:19 UTC by pchemguy

Use parse_json helper to enable the use of the object form of "shell" with JSON containing menu items.

2024-06-20 08:45 UTC, lovasoa requested changes

2024-06-20 08:45 UTC, lovasoa commented on sqlpage/templates/shell.handlebars
> +                            {{#with (parse_json this)}}
This parses the same json string twice

2024-06-20 10:30 UTC, pchemguy commented
There was another issue. `'Help' AS menu_item` would be passed to parse_json causing an unhandled error. So I had to create a more elaborate check removing the first parse_json and only keeping it in the "with" block where a preliminary check is passed.

2024-06-21 09:47 UTC, lovasoa commented
This is super useful ! 

Can we add an example to the documentation for these "conditional" menu items ? Otherwise people would never know the possibility even exists.

2024-06-21 15:49 UTC, pchemguy commented
I have added a basic example. A more elaborate example will be a part of separate pull request.

2024-06-21 17:37 UTC, merged