Merge & correct the layout of the sidebar
lovasoa/SQLpage pull request #523
Opened 2024-08-10 10:57 UTC by Ajotah98

I changed the layout to correct the grid problem on the header.

Also, I wasn't aware that the sidebar view also had the same problem for long titles, so I added a display inline that makes a better UI (in my opinion)

2024-08-10 19:41 UTC, lovasoa commented
@Ajotah98 , I think you have a formatter that changed a bunch of files that are not related to the PR. Can you revert the formatting changes and keep only the actual shell component updates?

2024-08-12 16:09 UTC, lovasoa requested changes

2024-08-12 16:09 UTC, lovasoa commented on sqlpage/templates/shell.handlebars
> +                <h1 class="navbar-brand navbar-brand-autodark" style="display:inline;">
can we use a bootstrap class instead of an inline style ?

2024-08-15 06:16 UTC, lovasoa commented
additionnally, this seems to break long titles ellipsis

![image](https://github.com/user-attachments/assets/53fa4e8d-86c2-45f1-9ca7-51db70c1dad9)

2024-08-15 12:57 UTC, lovasoa commented
Ok, I think everything is fixed now

2024-08-15 13:57 UTC, merged

2024-08-16 15:55 UTC, Ajotah98 commented
I apologize!! I couldn't see this until today. 

I'm grateful you managed to repair the broken things, and so sorry for breaking the title.
Thanks!!